### ISSUE TITLE
`TypeError: cannot unpack non-iterable CreateTaskList object` in `babyagi.xircuits`

### ISSUE THREAD

**Issue by KastanDay** [XpressAI/xai-gpt-agent-toolkit#2]
Hi thank you for this very interesting interface. Any idea what I can do here? It's hard to tell what arguments are being passed into `main()`. Thanks for the help.

I was very careful to follow the install instructions exactly.

![CleanShot 2023-04-19 at 16 12 01](https://user-images.githubusercontent.com/13607221/233201308-d4b603c9-c37e-4332-80ac-800370ac1173.png)

**Comment by DcMbse** [comment]
I have exactly the same error. Ubuntu Server 22.04. Followed all steps, double checked. 
Running toolkit with xircuits --ip xxx.xxx.xxx.xxx

**Comment by wmeddie** [comment]
Hi.  Sorry about this issue.  We are in the middle of a refactoring in Xircuits and the xircuits-components command grabs the latest from main and not the currently installed xircuits version.  If you re-run the installation steps but use `xircuits-components --branch=v1.7.1` that should bring in the old version that should work.

I've updated the command in the README.

**Comment by wmeddie** [comment]
Now that 1.8 is released this issue should be gone now.  Thanks for reporting.
