### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'do'

### ISSUE THREAD

**Issue by igor17400** [XpressAI/xai-gpt-agent-toolkit#3]
I followed all the steps shown on the README.md file. However, when I tried to execute the project by pressing the "play" button the error shown on the image below occurs:

<img width="449" alt="Screenshot 2023-05-22 at 15 52 32" src="https://github.com/XpressAI/xai-gpt-agent-toolkit/assets/42355184/b4bdd7b4-6929-4cb3-899a-79007a20b1b1">

**Comment by wmeddie** [comment]
Ah I need to update the readme to work with the latest release.  I think it can be fixed by clearing out the xai_components folder and running the `xircuits-components` command but without the ` --branch=v1.7.1`

I'll check that that is the case and respond again here.

**Comment by igor17400** [comment]
I executed the `xircuits-components` command but without the  
`--branch=v1.7.1` and it worked!

Thank you for the support :)

**Comment by wmeddie** [comment]
I've confirmed it too.  Updated the readme just now.
